[package]
name = "raptors-python"
version = "0.3.0"
edition = "2021"
autotests = false
exclude = [".venv/**", ".venv-release-*/**"]

[lib]
name = "raptors"
crate-type = ["cdylib"]
path = "src/preview_lib.rs"

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module", "num-complex", "abi3-py312"] }
raptors-storage = { path = "../raptors-storage" }
raptors-longdouble = { path = "../raptors-longdouble" }

[build-dependencies]
pyo3-build-config = "0.27"

[dev-dependencies]
pyo3 = { version = "0.27", features = ["extension-module", "num-complex", "auto-initialize", "abi3-py312"] }
